# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d71a0fa36f2fbed94dcdc5152b3ade1106eefa82cdd97db3d310e580da597afec5e72f5da6228d225f6fc7a577d135fdc655f26bc6a4d1bbe9b9752bc304289a

test:
  secret_key_base: 5f7978cc2be48d829a337a7f17f23537d1b9fbc12e526d25b8736e8929f5ea8e15970a72f8f4b4daaf0f7fd26ae0c8b9d3cd54f5b2070d74e0f8812240f84132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
